parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  es6: true
  sourceType: module
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
plugins:
  - '@typescript-eslint/eslint-plugin'
  - unused-imports
root: true
env:
  node: true
  jest: true
rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  unused-imports/no-unused-imports: error
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      ignoreRestSiblings: false
